### ISSUE TITLE
Would it be possible to explain a bit more how it works in the README?

### ISSUE THREAD

**Issue by cymen** [haoliangyu/pg-reactive#1]
I follow pg-promise and I saw your issue there -- your project is very interesting to me. I was curious though how does `subscribe` work? Does it poll the database for changes? Or is it using PostgreSQLs NOTIFY? I'll go dig in the source some more but it would be great to have a brief description in the README.

Thanks!

**Comment by vitaly-t** [comment]
> and I saw your issue there

@cymen could you, please add a link to the issue you are referring to?

**Comment by haoliangyu** [comment]
@vitaly-t I do like `pg-promise` and use it a lot at work. But I still share the [same concern](https://github.com/brianc/node-postgres/issues/915#issuecomment-171867947) of @jadbox, who developed the [pg-rxjs](https://www.npmjs.com/package/pg-rxjs). I also feel like `pg-promise` is too big to be a dependency if all I want is a observable wrapper of `pg`.

**Comment by vitaly-t** [comment]
@haoliangyu Well, the concern about the package size these days only has merit when it is for the client-side. But since `pg-promise` is strictly a server-side package its 400KB size is nothing. It is even smaller than many client-side packages these days. So really, I do not understand your concerns here.

**Comment by cymen** [comment]
@vitaly-Ah! I confused pg-promise with node-postgres while reading my email. It was [this issue](https://github.com/brianc/node-postgres/issues/1343). I only mentioned it in passing because I was trying to explain I was coming from the PostgreSQL side in finding this project not the RxJS/Rx side.

@haoliangyu Thank you. I think I misunderstood -- I assumed when reading the example in the README that `subscribe` would end up emitting updates when new rows where inserted into `user`. I'm thinking now that I was wrong about that. But I'm still unclear so brief detail would be great or maybe this is just a general Rx/RxJS question and out of scope of this project.

**Comment by haoliangyu** [comment]
@vitaly-t I think you are right and I may overthink. I will consider to rebase this project on `pg-promise` when I need to develop more complex features that can leverage `pg-promise`.

**Comment by vitaly-t** [comment]
@haoliangyu I will help you with that ;)

**Comment by haoliangyu** [comment]
@cymen Having some RxJS knowledge would be good to understand this library. I have added a [how-it-works](https://github.com/haoliangyu/pg-reactive#how-it-works) section at readme and hope it make senses :-)

**Comment by cymen** [comment]
@haoliangyu Thank you, that makes sense to me.
