### ISSUE TITLE
RxJS 6 Support

### ISSUE THREAD

**Issue by JKing-B16** [haoliangyu/pg-reactive#10]
Will you be releasing an updated version of the library that supports RxJS 6?

**Comment by haoliangyu** [comment]
:+1:  I have been away from rxjs development for a while and does not notice rxjs v6 is out. I will add it into my todo list.

**Comment by haoliangyu** [comment]
@JKing-B16 You can try the latest version (v1.0.0) now. Please let me know if it does not work for you.
