### ISSUE TITLE
Map doesn't exist

### ISSUE THREAD

**Issue by anzileiro** [haoliangyu/pg-reactive#16]
Hi could you help me please?

I'm trying to use this package to make queries on postgresql but I got:

<img width="447" alt="Screen Shot 2020-04-04 at 21 41 12" src="https://user-images.githubusercontent.com/3415671/78464233-27644280-76bd-11ea-8559-9461f3b6fc6e.png">

Thanks :)

**Comment by athomann** [comment]
The latest version of RxJS uses `.pipe` function now and removed direct chaining of operators.  The docs could be updated to reflect that.

**Comment by haoliangyu** [comment]
I have updated the README as suggested.
